services:
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: sqlserver
    environment:
      SA_PASSWORD: "Pa$$w0rd14"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - app_net
    volumes:
      - db_data:/var/opt/mssql

  my_python_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_python_app
    depends_on:
      - db
    networks:
      - app_net
    environment:
      - DB_HOST=db
      - DB_USER=sa
      - DB_PASSWORD=Pa$$w0rd14
      - DB_NAME=master

networks:
  app_net:
    driver: bridge

volumes:
  db_data:
